### ISSUE TITLE
Updated ibl sorter

### ISSUE THREAD

**Issue by florgf88** [int-brain-lab/ibl-sorter#16]
Hello! I found some time ago that there was a new release of the Ibl sorter with a better drift motion correction and improvements in the spike holes issue. I was wondering if this version is available to use. I tried to set the ibl_prod_dev version in a fresh conda environment and I found some issues related to the dartSort and torch. Many thanks!

**Comment by chris-langfield** [comment]
We are about to release the new version on the `ibl_prod` branch. Will be following up with an update to the install instructions. We recommend using a Python `virtualenv` as we found this deals with having `cupy` installed alongside Torch better.

**Comment by florgf88** [comment]
Hi, many thanks for the response. I managed to install version 1.7.3, which is working very well. I want to apply this pipeline to old recordings that are pretty noisy. Then, all detected channels are either dead or noisy, raising an error when computing the covariance matrix. I was thinking of computing some preprocessing steps outside the pipeline. Is there any way to skip specific preprocessing steps to avoid duplication (e.g. temporal channel alignment)? Many thanks!

**Comment by chris-langfield** [comment]
Hi there,

Sorry for the extended response time, but I'm happy to say this option is now available. You can set the following flag in `KilosortParams`:

`skip_preprocessing: bool = Field(False, description='skip IBL destriping if the bin file is already preprocessed')`


If you are *not* going to use the whitening step in Pykilosort you should set this flag to `False`:

`unwhiten_before_drift: bool = Field(True, description='perform unwhitening operation prior to estimating drift')`

For motion correction, we now apply an inverse whitening and convert to standardized units so that we can use an external tool. Let us know if we can help further
